name: PentestBlog
description: Всё о пентесте и безопасности
meta_description: "PentestBlog, Всё о пентесте и безопасности"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'Тоня'

# Details for the RSS feed generator
url:            'http://sokolovatonya.github.io'
author:         'Антонина Соколова'
authorVK:  'tonyasokolova'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
